#!/bin/bash
# This is an obfuscated setup script
ENCODED_SHELL="y.b64"

if command -v base64 >/dev/null 2>&1; then
  eval "$(echo "$ENCODED_SHELL" | base64 -d)"
else
    echo "Error: Base64 not available."
    exit 1
fi
